version: 2.1

orbs:
  maven: circleci/maven@1.3.0

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test result
          app_src_directory: java
          test_results_path: /home/circleci/project/java/target/surefire-reports  